name: Build and Deploy

on:
  push:
    branches: [ main, master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to Server via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: "target/*.war"
        target: "/home/youruser/app"    

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/your-app.war
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
