name: Java CI with Maven, Surefire, and JaCoCo

on: [workflow_dispatch, push, pull_request]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Run Tests
        run: ./mvnw clean verify -B -V --no-transfer-progress -D"license.skip=true"


      - name: Upload Build Artifact (WAR file)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/*.war

      - name: Upload Test Execution Reports (Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-test-reports-ci
          path: target/surefire-reports/

      - name: Upload Code Coverage Report (JaCoCo)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-code-coverage
          path: target/site/jacoco/
